name: fluent_object_storage
description: A base package for simple object storage sdk.
version: 0.1.0
homepage: https://github.com/jiejie-dev/fluent_object_storage

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
